name: Generate 3D Contribution Graph Snake

on:
  push:
    branches:
      - main
  schedule: # Automatically update daily
      - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
