name: Generate 3D Contribution Graph Snake

on:
  push:
    branches:
      - main
  schedule: # Automatically update daily
      - cron: "0 0 * * *"

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          output: dist/github-contribution-grid-snake.svg
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
